
# registerWithEureka контролирует, регистрируется ли этот клиент сам себя и, следовательно,
# становится доступным для обнаружения . Это само по себе не означает, что этот клиент будет получать информацию
#  о конечных точках других служб и, следовательно, иметь возможность подключаться к ним.
#
# fetchRegistry контролирует, будет ли этот клиент пытаться подключиться к серверу (-ам) Eureka,
# чтобы загрузить информацию о конечной точке других служб. Он может сделать это без регистрации


eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
server:
    port: 8761
spring:
    application:
        name: discovery-server

